### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bjeanes** [mdub/representative_view#10]
Hi, I'm doing a licence audit on a codebase that uses this gem but this gem doesn't appear to have a licence.

Would you be willing to specify your preferred licence or add a `LICENCE` file? I understand this repository may no longer be maintained, but it would be a great help if you could clarify your wishes here.

I would take it implicitly that this is MIT on the basis that the related gem [`representative` is MIT](https://github.com/mdub/representative/blob/master/LICENSE), but I'd prefer this to be explicit.

**Comment by mdub** [comment]
A sterling idea. Hold my beer.
